/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab05_FTPClient_bai10;

import java.awt.HeadlessException;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Khang's PC
 */
public class frmHienThi extends javax.swing.JInternalFrame {
    private Socket socket = null;
    private PrintWriter out = null;
    private Scanner in = null;
    private String username = "";
    private String password="";
    private String path="";
    /**
     * Creates new form frmHienThi
     */
    public frmHienThi() {
        initComponents();
    }
    public frmHienThi(Socket s, String username, String password) {
        initComponents();
        this.socket=s;
        
        this.setTitle("Xin chào "+username);
        this.username = username;
        this.password = password;
        loadlist();
    }

    public void loadlist(){
        try {
            BufferedInputStream bi = new BufferedInputStream(socket.getInputStream());
            in = new Scanner(bi);
            DefaultListModel dm = new DefaultListModel();
            int n = in.nextInt();
            for(int i=0; i<=n; i++){
                String filename = in.nextLine();
                dm.addElement(filename);
            }
            this.listUserFolder.setModel(dm);
            listUserFolder.setSelectedIndex(0);
            this.validate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserClient = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        listClientFolder = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUserFolder = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnBrowser = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        listClientFolder.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listClientFolder);

        jLabel1.setText("Current Folder at Client");

        btnUp.setText("Upload");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnDown.setText("Download");
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        listUserFolder.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listUserFolder);

        jLabel2.setText("Your account's Folder on server");

        btnBrowser.setText("Browser");
        btnBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowserActionPerformed(evt);
            }
        });

        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBrowser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBrowser)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDown))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowserActionPerformed
        // TODO add your handling code here:
        this.fileChooserClient.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(this.fileChooserClient.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            try {
                //lấy đường dẫn
                path = this.fileChooserClient.getSelectedFile().getCanonicalPath();
                File dir = new File(path);
                File dsFile[]=dir.listFiles();
                if(dsFile==null){
                    JOptionPane.showMessageDialog(null, "Đường dẫn không đúng hay không phải thư mục");
                }else{
                    DefaultListModel dm = new DefaultListModel();
                    for(int i=0; i<dsFile.length; i++){
                        String filename=dsFile[i].getName();
                        dm.addElement(filename);
                    }
                    this.listClientFolder.setModel(dm);
                    listClientFolder.setSelectedIndex(0);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnBrowserActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        String str = "upload@"+"select * from taikhoan where username='"+username+"'@";
        String filename;
        
        if(!path.equals("")){
            try {
                filename = listClientFolder.getSelectedValue().toString();
                File f = new File(path+"\\"+filename);
                str = str+filename;
                out = new PrintWriter(socket.getOutputStream(),true);
                out.println(str+"@"+(int)f.length());
                
                byte[] mybytearray = new byte[(int) f.length()];
                BufferedInputStream bis = new BufferedInputStream(new FileInputStream(f));
                bis.read(mybytearray, 0, mybytearray.length);
                OutputStream os = socket.getOutputStream();
                os.write(mybytearray, 0 , mybytearray.length);
                os.flush();
                bis.close();
                loadlist();
            } catch (Exception e) {
                try {
                    if(socket!=null)    socket.close();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn file","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        // TODO add your handling code here:
        String str = "download@" + "select * from taikhoan where username='" + username + "'@";
        String filename;
        try {
            //Truyền lệnh lên server yêu cầu file
            filename = listUserFolder.getSelectedValue().toString();
            str = str + filename;
            out = new PrintWriter(socket.getOutputStream(), true);
            out.println(str);
            //Nhận file từ server về lưu trong path
            BufferedInputStream bi = new BufferedInputStream(socket.getInputStream());
            in = new Scanner(bi);
            int doDaiFile = in.nextInt();//lay do dai file
            if (path.equals("")) {
                this.fileChooserClient.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                if (this.fileChooserClient.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                    path = this.fileChooserClient.getSelectedFile().getCanonicalPath();
                }
            }
            int bytesRead;
            int current = 0;
            File f = new File(path + "\\" + filename);
            byte[] mybytearray = new byte[doDaiFile];
            InputStream is = socket.getInputStream();
            FileOutputStream fos = new FileOutputStream(f);
            try (BufferedOutputStream bos = new BufferedOutputStream(fos)) {
                bytesRead = is.read(mybytearray, 0, mybytearray.length);
                current = bytesRead;
                while (current != doDaiFile) {
                    bytesRead = is.read(mybytearray, current, mybytearray.length - current);
                    if (bytesRead >= 0) {
                        current += bytesRead;
                    }
                }
                bos.write(mybytearray, 0, current);
                bos.flush();
            }
            File dir = new File(path);
            File dsFile[] = dir.listFiles();
            DefaultListModel dm = new DefaultListModel();
            for (File dsFile1 : dsFile) {
                String name = dsFile1.getName();
                dm.addElement(name);
            }
            this.listClientFolder.setModel(dm);
            listClientFolder.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "dowload tệp tin về thành công");
        } catch (HeadlessException | IOException e) {
            try {
                if (socket != null) {
                    socket.close();
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "dowload tệp tin thất bại");
            }
        }
    }//GEN-LAST:event_btnDownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowser;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnUp;
    private javax.swing.JFileChooser fileChooserClient;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listClientFolder;
    private javax.swing.JList<String> listUserFolder;
    // End of variables declaration//GEN-END:variables
}
